let Vat_ly;
let Hoa_hoc;
let Sinh_hoc;
Vat_ly = parseFloat(prompt('Nhập điểm lý'));
Hoa_hoc = parseFloat(prompt('Nhập điểm hoá'));
Sinh_hoc = parseFloat(prompt('Nhập điểm sinh'));
let Tong = Vat_ly+Hoa_hoc+Sinh_hoc;
let tb = (Vat_ly+Hoa_hoc+Sinh_hoc)/3;
document.write('tong = ' + Tong, "</br>");
document.write('trung binh = ' + tb);
